// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR8TueaG0DtQaeYbJ9qdsrJnODj9Qnnkk',
    appId: '1:646667608294:web:6338d6340f82d685de5b27',
    messagingSenderId: '646667608294',
    projectId: 'henna-6c6ff',
    authDomain: 'henna-6c6ff.firebaseapp.com',
    storageBucket: 'henna-6c6ff.firebasestorage.app',
    measurementId: 'G-RC17M04X4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3P41wczdZhJq1NmKRFegH5ruLcIKxL8',
    appId: '1:646667608294:android:7756023a32c62a69de5b27',
    messagingSenderId: '646667608294',
    projectId: 'henna-6c6ff',
    storageBucket: 'henna-6c6ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_vHHHktR1ew7RdOC8jDghrZni9b7zeI',
    appId: '1:646667608294:ios:fda15aee53f70b51de5b27',
    messagingSenderId: '646667608294',
    projectId: 'henna-6c6ff',
    storageBucket: 'henna-6c6ff.firebasestorage.app',
    iosBundleId: 'com.example.hennaByBasith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR8TueaG0DtQaeYbJ9qdsrJnODj9Qnnkk',
    appId: '1:646667608294:web:6cc8f847b9764c87de5b27',
    messagingSenderId: '646667608294',
    projectId: 'henna-6c6ff',
    authDomain: 'henna-6c6ff.firebaseapp.com',
    storageBucket: 'henna-6c6ff.firebasestorage.app',
    measurementId: 'G-H9BLHDN3DS',
  );
}
